spring:
    profiles: 
        active: server     
    devtools:
        restart:
            pollInterval: 5s   
            
server:
    port: 80
    servlet:
        context-path: /vezerles             
    
    
        

